### ISSUE TITLE
Add suport for Artemis artemis-amqp-client feature

### ISSUE THREAD

**Issue by johnpoth** [ops4j/org.ops4j.pax.jms#5]
We should support [artemis-amqp-client](https://github.com/apache/activemq-artemis/blob/master/artemis-features/src/main/resources/features.xml#L81) feature. The desired protocol could be choosen via some configuration property.

Note that the underlying library used (qpid-jms-client) doesn't support XAConnection which is eagerly created in PAX-JMS and is likely to cause problems.

**Comment by grgrzybek** [comment]
#7 is merged.
