### ISSUE TITLE
Add support for https://github.com/messaginghub/pooled-jms

### ISSUE THREAD

**Issue by johnpoth** [ops4j/org.ops4j.pax.jms#6]
Currently connection pooling is provided by [GenericConnectionManager.java](https://github.com/ops4j/org.ops4j.pax.transx/blob/master/pax-transx-connector/src/main/java/org/ops4j/pax/transx/connector/impl/GenericConnectionManager.java). It might be nice to be able to use https://github.com/messaginghub/pooled-jms instead which was [intented](https://issues.apache.org/jira/browse/ARTEMIS-469) for artemis clients

**Comment by grgrzybek** [comment]
#3 is merged
